---

- sysctl:
    name: "{{ item }}"
    value: 1
    sysctl_set: yes
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6

- name: Prepare yum mirror repo files
  include_role:
    name: yum-repos-prepare

- name: Create docker configuration directory
  file:
    path: /etc/docker/
    state: directory

- name: Set up docker bridge network
  template:
    src: docker/daemon.json.j2
    dest: /etc/docker/daemon.json

- name: Provision OpenContrail using contrail-ansible-deployer role
  include_role:
    name: contrail-ansible-deployer
