---

- name: Deploy controller VMs for testenv '{{ testenv_name }}' using API directly
  delegate_to: localhost
  shell: >
    '{{ script_path.path }}/provision_vm.py'
    --host '{{ vcenter_hostname }}'
    --user '{{ vcenter_user }}'
    --password '{{ vcenter_password }}'
    --datacenter '{{ datacenter_name }}'
    --datastore-cluster '{{ datastore_cluster_name }}'
    --template '{{ hostvars[inventory_hostname].template }}'
    --folder '{{ testenv_folder }}'
    --name '{{ inventory_hostname_short }}'
    --mgmt-network '{{ portgroup_mgmt }}'
    --data-network '{{ portgroup_contrail }}'
    --data-ip-address '172.16.0.1'
    --data-netmask '255.255.0.0'
