---
- name: Check testenv name
  fail:
    msg: testenv_name is too long; should be 7 characters or less
  when: testenv_name|length > 7

- name: Add testenvs VMs to ad-hoc inventory for testenv '{{ testenv_name }}'
  add_host:
    name: "{{ item.name }}"
    type: "{{ item.type }}"
    groups: "testenv,{{ item.groups }}"
    template: "{{ item.template }}"
    ip: "{{ item.ip }}"
    netmask: "{{ item.netmask }}"
    testenv_name: "{{ testenv_block.name }}"
    testenv_folder: "{{ testenv_block.folder }}"
    portgroup_mgmt: "{{ testenv_block.portgroup_mgmt }}"
    portgroup_contrail: "{{ testenv_block.portgroup_contrail }}"
    vm_username: "{{ item.vm_username | default(None) }}"
    vm_password: "{{ item.vm_password | default(None) }}"
  with_items:
    "{{ testenv_block.vms }}"
  no_log: true

- name: Display inventory for 'testenv' group
  debug:
    verbosity: 1
    msg: "{{ item }}, groups: {{ hostvars[item].group_names }}"
  with_inventory_hostnames: testenv
