---

- name: Include jenkins-partition role
  include_role:
    name: jenkins-partition

- name: Include windows-ntp role
  include_role:
    name: windows-ntp

- name: Install git with chocolatey
  win_chocolatey:
    name: git
    state: present

- name: Install .Net Framework 3.5
  win_feature:
    name: Net-Framework-Core
    state: present

- name: Remove Hyper-V PowerShell module
  win_psmodule:
    name: Hyper-V
    state: absent
  ignore_errors: yes # If windows wasn't installed with that, it won't show and will fail

- name: Install PowerCLI PowerShell module
  win_psmodule:
    name: VMWare.PowerCLI
    state: present

- name: Install PowerShell YAML parser module
  win_psmodule:
    name: powershell-yaml
    state: present

- name: Check TrustedHosts value
  win_shell: (Get-Item WSMan:\localhost\Client\TrustedHosts).Value
  register: trusted_hosts

- name: Set Testbeds as TrustedHosts
  win_shell: >
    Set-Item WSMan:\localhost\Client\TrustedHosts
    -Value "{{ (((trusted_hosts.stdout | trim()).split(',') | reject('equalto', '') | list()) + ['172.17.0.*']) | join(',') }}"
    -Force
  when: not (trusted_hosts.stdout | search("172.17.0.*"))

- name: Install Pester 4.2.0 (override default installation)
  # We need to do it like this due to https://github.com/pester/Pester/wiki/Installation-and-Update#installing-from-psgallery-windows-10-or-windows-server-2016
  win_shell: 'Install-Module -Name Pester -Force -SkipPublisherCheck -RequiredVersion 4.2.0'

- name: Install NuGet with chocolatey
  win_chocolatey:
    name: nuget.commandline
    state: present
    version: 4.5.1

- name: Install ReportUnit with NuGet
  win_shell: >
    nuget install ReportUnit -Version 1.5.0-beta1 -OutputDirectory C:\
  args:
    creates: C:\ReportUnit.1.5.0-beta1

- name: Add ReportUnit to PATH
  win_path:
    elements:
    - C:\ReportUnit.1.5.0-beta1\tools
    state: present

- name: Include telegraf role
  include_role:
    name: telegraf
