---

- name: Install build dependencies
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - ansible
    - git
    - python-pip

- name: (HACK) Update MarkupSafe
  pip:
    name: MarkupSafe
    version: 1.0.0
  become: true

- name: Clone contrail-ansible-deployer repository
  git:
    repo: 'https://github.com/Juniper/contrail-ansible-deployer'
    dest: "{{ docker_provision_dir }}"
    version: "{{contrail_ansible_deployer_version }}"
    force: yes

- name: Copy hosts template
  template:
    src: instances.j2
    dest: "{{ docker_provision_dir }}/config/instances.yaml"

- name: Configure instances with configure_instances.yml playbook
  command: ansible-playbook -i inventory/ playbooks/configure_instances.yml -v
  args:
    chdir: "{{ docker_provision_dir }}"
  environment:
    ANSIBLE_HOST_KEY_CHECKING: 'False'
    ANSIBLE_STDOUT_CALLBACK: debug
  become: True
  tags:
    - skip_ansible_lint # ANSIBLE0012: Commands should not change things if nothing needs doing
                        # Always run internal playbook: we cannot easily recognize here if it changed something.

- name: Provision instances with install_contrail.yml playbook
  command: ansible-playbook -i inventory/ -e orchestrator=openstack playbooks/install_contrail.yml
  args:
    chdir: "{{ docker_provision_dir }}"
  environment:
    ANSIBLE_HOST_KEY_CHECKING: 'False'
    ANSIBLE_STDOUT_CALLBACK: debug
  become: True
  tags:
    - skip_ansible_lint # ANSIBLE0012: Commands should not change things if nothing needs doing
                        # Always run internal playbook: we cannot easily recognize here if it changed something.

- name: Show the list of running containers
  command: docker ps -a
  become: True
  changed_when: False

- name: Show processes
  command: ps aux --sort rss
  changed_when: False

- name: Show memory usage
  command: free -m
  changed_when: False

- name: Check interfaces for addresses
  command: ip addr
  become: True
  changed_when: False

- name: (Hack) get config_api container id
  shell: docker ps | awk '/config_api/ { print $1 }'
  register: config_api_container
  become: True
  changed_when: False

- name: (Hack) restart config_api container to fix issue with VNC API lib
  command: docker restart {{ config_api_container.stdout }}
  become: True
  when: config_api_container.stdout is defined
